# Generated by Django 3.0.7 on 2020-07-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prison2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=25)),
                ('Title', models.CharField(max_length=30)),
                ('Status', models.CharField(max_length=15)),
            ],
        ),
    ]
