# Generated by Django 3.0.7 on 2020-07-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='prison2',
            new_name='Prisoner_Officer',
        ),
    ]
