# Generated by Django 3.0.7 on 2020-07-04 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0002_auto_20200704_2031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prisoner_Officer',
            new_name='Prisoner_Officer2',
        ),
    ]
