# Generated by Django 3.0.7 on 2020-07-05 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0003_auto_20200704_2056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prisoner_Officer2',
            new_name='Prisoner_Officer',
        ),
    ]
