# Generated by Django 3.0.7 on 2020-07-08 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0004_auto_20200705_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='prisoner_officer',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
