# Generated by Django 3.0.7 on 2020-07-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0005_prisoner_officer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Today_Top_News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('TopDate', models.DateField(auto_now_add=True)),
                ('Heading', models.CharField(max_length=30)),
            ],
        ),
    ]
