# Generated by Django 3.0.7 on 2020-07-09 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0006_today_top_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prisoner_Officer',
        ),
    ]
