# Generated by Django 3.0.7 on 2020-07-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0007_delete_prisoner_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='today_top_news',
            name='Heading',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='today_top_news',
            name='TopDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
