# Generated by Django 3.0.7 on 2020-07-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0008_auto_20200709_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('Detail', models.CharField(max_length=200)),
            ],
        ),
    ]
