# Generated by Django 3.0.7 on 2020-07-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0009_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.CharField(max_length=60, verbose_name='first_name')),
                ('Surname', models.CharField(max_length=30, verbose_name='Surname')),
                ('Idetification_Number', models.CharField(max_length=30, verbose_name='ID_NO')),
                ('Phone_Number', models.IntegerField(verbose_name='Phone_No')),
                ('Date_of_Birth', models.DateField(verbose_name='DOB')),
                ('password', models.CharField(max_length=30, verbose_name='Pswd')),
            ],
        ),
    ]
