# Generated by Django 3.0.7 on 2020-07-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0010_registration_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_form',
            name='Date_of_Birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registration_form',
            name='Idetification_Number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='registration_form',
            name='Phone_Number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registration_form',
            name='Surname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='registration_form',
            name='first_names',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='registration_form',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
