# Generated by Django 3.0.7 on 2020-07-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0011_auto_20200715_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
