# Generated by Django 3.0.7 on 2020-07-15 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0012_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
