# Generated by Django 3.0.7 on 2020-07-16 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0014_auto_20200716_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='first_names',
            new_name='email',
        ),
        migrations.AddField(
            model_name='registration',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
    ]
