# Generated by Django 3.0.7 on 2020-07-25 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PMS', '0015_auto_20200716_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Idetification_Number', models.CharField(max_length=30)),
                ('Phone_Number', models.IntegerField()),
                ('Date_of_Birth', models.DateField()),
                ('Address', models.CharField(max_length=30)),
                ('Profile_image', models.ImageField(blank=True, default='p.jpg', null=True, upload_to='images/users')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
