# Generated by Django 3.0.7 on 2020-07-25 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0016_auto_20200725_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Phone_Number',
        ),
    ]
