# Generated by Django 3.0.7 on 2020-07-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0018_auto_20200725_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_destination', models.CharField(max_length=30)),
                ('sidebar_offer_percent', models.CharField(max_length=8, null=True)),
                ('offer_title', models.CharField(max_length=10)),
                ('offer_text', models.CharField(max_length=30)),
                ('image', models.ImageField(default='PMS/images/89238244.jpg', null=True, upload_to='images/offers')),
                ('Date_of_Birth', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
