# Generated by Django 3.0.7 on 2020-07-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0019_posters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posters',
            name='offer_text',
            field=models.CharField(max_length=60),
        ),
    ]
