# Generated by Django 3.0.7 on 2020-07-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0020_auto_20200726_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posters',
            old_name='Date_of_Birth',
            new_name='Poster_Date',
        ),
    ]
