# Generated by Django 3.0.7 on 2020-07-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0021_auto_20200726_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posters',
            name='image',
            field=models.ImageField(default='../PMS/images/89238244.jpg', null=True, upload_to='images/offers'),
        ),
    ]
