# Generated by Django 3.0.7 on 2020-08-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0022_auto_20200726_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SlideImg', models.ImageField(upload_to='images/')),
                ('SlideTitle', models.CharField(max_length=50)),
                ('TopDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
