# Generated by Django 3.0.7 on 2020-08-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0023_home_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_slide',
            name='SlideTitle',
            field=models.CharField(max_length=100),
        ),
    ]
