# Generated by Django 3.0.7 on 2020-08-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0024_auto_20200808_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_slide',
            name='SlideImg',
            field=models.ImageField(upload_to='images/Slide'),
        ),
    ]
