# Generated by Django 3.0.7 on 2020-08-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0025_auto_20200808_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=15, null=True)),
                ('subject', models.CharField(max_length=20)),
            ],
        ),
    ]
