# Generated by Django 3.0.7 on 2020-08-26 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0026_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('Case_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Case_Type', models.CharField(max_length=10)),
                ('Case_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('Cell_ID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Prisoner',
            fields=[
                ('Prisoner_ID', models.AutoField(primary_key=True, serialize=False)),
                ('First_Names', models.CharField(max_length=60)),
                ('Surname', models.CharField(max_length=10)),
                ('DoB', models.DateField()),
                ('Date_In', models.DateField(auto_now_add=True)),
                ('Choose_Gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], default='M', max_length=6)),
                ('Status', models.CharField(default='Normal', max_length=10, null=True)),
                ('Cell_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMS.Cell')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('Visitor_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Card_Number', models.CharField(max_length=4)),
                ('Prisoner_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PMS.Prisoner')),
            ],
        ),
        migrations.CreateModel(
            name='Prisoner_Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Case_ID', models.ManyToManyField(to='PMS.Case')),
                ('Prisoner_ID', models.ManyToManyField(to='PMS.Prisoner')),
            ],
        ),
        migrations.CreateModel(
            name='Prison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prison_Name', models.CharField(max_length=60)),
                ('Address', models.CharField(max_length=60)),
                ('Prison_ID', models.ManyToManyField(to='PMS.Prisoner')),
            ],
        ),
    ]
