# Generated by Django 3.0.7 on 2020-08-26 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0027_case_cell_prison_prisoner_prisoner_case_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisoner',
            name='Cell_ID',
            field=models.ForeignKey(default='Robbary', on_delete=django.db.models.deletion.CASCADE, to='PMS.Cell'),
        ),
    ]
