# Generated by Django 3.0.7 on 2020-08-26 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0028_auto_20200826_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prisoner',
            name='Cell_ID',
        ),
        migrations.AddField(
            model_name='cell',
            name='Cell_Name',
            field=models.CharField(choices=[('Cell1', 'QR'), ('Cell2', 'qz')], default='Cell1', max_length=6),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='Cell_Name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PMS.Cell'),
            preserve_default=False,
        ),
    ]
