# Generated by Django 3.0.7 on 2020-08-26 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0030_auto_20200826_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisoner',
            name='Cell_Name',
            field=models.OneToOneField(default='Cell1', on_delete=django.db.models.deletion.CASCADE, to='PMS.Cell'),
        ),
    ]
