# Generated by Django 3.0.7 on 2020-08-26 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0032_auto_20200826_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='Cell_Name',
            field=models.CharField(default='Cell1', max_length=6),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='Cell_Name',
            field=models.OneToOneField(default='Normal', null=True, on_delete=django.db.models.deletion.CASCADE, to='PMS.Cell'),
        ),
    ]
