# Generated by Django 3.0.7 on 2020-08-26 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0033_auto_20200826_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prisoner',
            old_name='Cell_Name',
            new_name='Cell_ID',
        ),
    ]
